name: tava
description: A practice journal for musicians

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^4.2.0
  google_fonts: any



  cupertino_icons: ^1.0.4
  date_picker_timeline: any
  slide_to_confirm: ^1.1.0
  flutter_onboarding_slider: ^1.0.7
  syncfusion_flutter_gauges: ^20.1.47
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  flutter_local_notifications: ^9.4.0
  geolocator: ^8.2.0
  flutter_native_splash: ^2.1.3+1
  connectivity_plus: ^2.2.1
  share_plus: ^4.0.3
  go_router: ^3.0.6
  feedback: ^2.4.1
  firebase_auth: ^3.3.12
  firebase_messaging: ^11.2.12
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  font_awesome_flutter: ^10.1.0
  flutter_slidable: ^1.2.0
  just_audio: ^0.9.20
  sign_in_with_apple: ^3.3.0
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13
  http: ^0.13.4
  image_picker: ^0.8.4+11
  fluttertoast: ^8.0.9
  carousel_slider: ^4.0.0
  weather: ^2.0.1
  shake: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_hooks: ^0.18.2+1
  flutter_riverpod: ^1.0.3
  persistent_bottom_nav_bar: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


