name: tava
description: A musician's practice journal with customizable metronome and progress tracking.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  
  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # UI
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  intl: ^0.20.2
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  flex_color_scheme: ^8.2.0
  
  # Cross-platform UI
  flutter_platform_widgets: ^9.0.0
  
  # Functional programming
  fpdart: ^1.1.1
  rxdart: ^0.28.0
  
  # Storage
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Backend
  connectivity_plus: ^6.1.4
  supabase_flutter: ^2.9.0

  # Metronome
  audio_session: ^0.2.2
  just_audio: ^0.10.4

  # Weather API
  geolocator: ^14.0.1
  weather: ^3.2.1

  # Other utilities
  logger: ^2.5.0
  uuid: ^4.5.1
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  go_router: ^15.2.3
  flutter_dotenv: ^5.2.1
  bloc: ^9.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  injectable_generator: ^2.3.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
    - .env